const PROPERTIES=[
  {
    id: 1,
    title: "Lodha Altamount",
    type: "Penthouse",
    location: "Altamount Road, Mumbai",
    city: "Mumbai",
    price: 450000000,
    bedrooms: 4,
    bathrooms: 5,
    sqft: 5500,
    garage: 3,
    image: "assets/prop_lodha.png",
    badge: "Ready to Move",
    lat: 18.9667,
    lng: 72.8083,
    yearBuilt: 2021,
    description: "Perched on India's most expensive street, this residence offers a weightless living experience with floor-to-ceiling glass walls. RERA: P51900000123",
    features: ["Private Elevator", "Infinity Sky Pool", "Global Concierge", "Automated Glass Facade", "Observatory Deck"]
  },
  {
    id: 2,
    title: "DLF The Camellias",
    type: "Penthouse",
    location: "Golf Course Road, Gurgaon",
    city: "Gurgaon",
    price: 750000000,
    bedrooms: 5,
    bathrooms: 6,
    sqft: 9500,
    garage: 4,
    image: "assets/prop_dlf.png",
    badge: "Ultra-Luxury",
    lat: 28.4595,
    lng: 77.0266,
    yearBuilt: 2022,
    description: "A masterpiece of modern minimalism where luxury meets the horizon across a 7-star clubhouse. RERA: GGM/351/83/2019",
    features: ["Internal Private Lift", "Olympic-size Sky Pool", "Chef’s Table Kitchen", "Cigar Lounge", "Smart Glass Tech"]
  },
  {
    id: 3,
    title: "Oberoi Three Sixty West",
    type: "Duplex",
    location: "Worli, Mumbai",
    city: "Mumbai",
    price: 620000000,
    bedrooms: 4,
    bathrooms: 5,
    sqft: 7200,
    garage: 3,
    image: "assets/prop_oberoi.png",
    badge: "Sea Facing",
    lat: 19.0176,
    lng: 72.8172,
    yearBuilt: 2023,
    description: "Rising majestically over the Worli seafront with panoramic 360-degree urban perspectives. RERA: P51900000567",
    features: ["Sea-Facing Gym", "Sky Forest Garden", "Ballroom", "Luxury Spa Retreat", "Business Sky-Lounge"]
  },
  {
    id: 4,
    title: "Prestige King's County",
    type: "Apartment",
    location: "Rajajinagar, Bangalore",
    city: "Bengaluru",
    price: 85000000,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 4200,
    garage: 2,
    image: "assets/prop_prestige.png",
    badge: "Under Construction",
    lat: 12.9880,
    lng: 77.5540,
    yearBuilt: 2025,
    description: "Architectural marvel featuring terraced gardens cascading like floating islands. RERA: PRM/KA/RERA/1251/310/PR/210302",
    features: ["Floating Yoga Pavilion", "Infinity Edge Pool", "Organic Sky Garden", "Library Cafe", "EV Charging Station"]
  },
  {
    id: 5,
    title: "Godrej Meridien",
    type: "Apartment",
    location: "Sector 106, Gurgaon",
    city: "Gurgaon",
    price: 42000000,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2700,
    garage: 2,
    image: "assets/prop_godrej.png",
    badge: "Lifestyle",
    lat: 28.5100,
    lng: 77.0300,
    yearBuilt: 2024,
    description: "Experience the high-life with a 66,000 sq. ft. clubhouse designed for the global citizen. RERA: RC/REP/HARERA/GGM/2018/05",
    features: ["Fine Dining Sky Restaurant", "Mini Theatre", "Olympic Size Pool", "Music Conservatory", "Wine Cellar"]
  },
  {
    id: 6,
    title: "Piramal Aranya",
    type: "Suite",
    location: "Byculla, Mumbai",
    city: "Mumbai",
    price: 120000000,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1800,
    garage: 2,
    image: "assets/prop_piramal.png",
    badge: "Rare Find",
    lat: 18.9800,
    lng: 72.8300,
    yearBuilt: 2022,
    description: "A confluence of botanical gardens and the deep blue sea, providing a serene escape. RERA: P51900003324",
    features: ["Botanical Sky Park", "Cricket Pitch", "Observation Deck", "Zen Fitness Center", "Pet Park"]
  },
  {
    id: 7,
    title: "Brigade Exotica",
    type: "Apartment",
    location: "Old Madras Road, Bangalore",
    city: "Bengaluru",
    price: 58000000,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3800,
    garage: 2,
    image: "assets/prop_brigade.png",
    badge: "Signature",
    lat: 13.0100,
    lng: 77.7200,
    yearBuilt: 2021,
    description: "Unique wing-like structure allowing for 3-side open views and cross-ventilation. RERA: PRM/KA/RERA/1251/446/PR/171014",
    features: ["Retail Sky Plaza", "Sports Arena", "Amphitheatre", "Clubhouse", "Smart Security"]
  },
  {
    id: 8,
    title: "Phoenix Kessaku",
    type: "Suite",
    location: "Rajajinagar, Bangalore",
    city: "Bengaluru",
    price: 150000000,
    bedrooms: 5,
    bathrooms: 5,
    sqft: 6500,
    garage: 3,
    image: "assets/prop_phoenix.png",
    badge: "Masterpiece",
    lat: 12.9800,
    lng: 77.5600,
    yearBuilt: 2022,
    description: "Kessaku offers a living experience grounded in Zen philosophy but reaching for the stars. RERA: PRM/KA/RERA/1251/310/PR/170916",
    features: ["Private Plunge Pool", "Cultural Sky Club", "Japanese Zen Garden", "Butler Service", "Gold-Class Cinema"]
  },
  {
    id: 9,
    title: "Pursuit of a Radical Rhapsody",
    type: "Villa",
    location: "Whitefield, Bangalore",
    city: "Bengaluru",
    price: 90000000,
    bedrooms: 4,
    bathrooms: 5,
    sqft: 5100,
    garage: 3,
    image: "assets/prop_rhapsody.png",
    badge: "Lake View",
    lat: 12.9600,
    lng: 77.7500,
    yearBuilt: 2024,
    description: "Each home features a sprawling terrace garden that seems to defy gravity. RERA: PRM/KA/RERA/1251/446/PR/171014",
    features: ["Terrace Garden", "Lake View Deck", "Community Sky Farm", "Craft Brewery", "Handcrafted Interiors"]
  },
  {
    id: 10,
    title: "M3M St. Andrews",
    type: "Penthouse",
    location: "Sector 65, Gurgaon",
    city: "Gurgaon",
    price: 65000000,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 4600,
    garage: 2,
    image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1200",
    badge: "Golf Course",
    lat: 28.4200,
    lng: 77.0600,
    yearBuilt: 2023,
    description: "Gravity-defying views of a 9-hole executive golf course from your glass balcony. RERA: 73 OF 2017",
    features: ["Golf Putting Green", "Sky Bar", "Temperature Controlled Pool", "Business Suite", "Private Cabanas"]
  }
];

const AGENTS=[
  {
    id:1,
    name:"Alexandra Chen",
    title:"Principal Broker",
    image:"assets/agent_portrait.png",
    phone:"+91 98765 43210",
    email:"alexandra@opensky.re",
    specialization:"Ultra-Luxury Estates",
    listings:47,
    sales:"₹2.4k Cr",
    rating:4.9
  },
  {
    id:2,
    name:"Marcus Rivera",
    title:"Senior Luxury Specialist",
    image:"assets/agent_portrait.png",
    phone:"+91 98765 43211",
    email:"marcus@opensky.re",
    specialization:"Penthouses",
    listings:31,
    sales:"₹890 Cr",
    rating:4.8
  },
  {
    id:3,
    name:"Sophia Laurent",
    title:"International Advisor",
    image:"assets/agent_portrait.png",
    phone:"+91 98765 43212",
    email:"sophia@opensky.re",
    specialization:"Waterfront",
    listings:28,
    sales:"₹1.1k Cr",
    rating:4.9
  }
];
